# Generated by Django 5.0.4 on 2025-03-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
